DROP TABLE METDB.MET_FACTMIBGAS;


CREATE TABLE METDB.MET_FACTMIBGASCAB (
    FMC_ID INT IDENTITY(1, 1) NOT NULL,
    FMC_SELLER VARCHAR(20) NOT NULL,
    FMC_BUYER VARCHAR(20) NOT NULL,
    FMC_INVNUM VARCHAR(50) NOT NULL,
    FMC_INVCOD VARCHAR(50),
    FMC_TIPFACT VARCHAR(5),
    FMC_TIPDOC VARCHAR(5),
    FMC_FECINV DATE,
    FMC_FECINI DATE,
    FMC_FECFIN DATE,
    FMC_FECVEN DATE,
    FMC_IMPBASE DECIMAL(15,2) NOT NULL,
    FMC_IMPTAX DECIMAL(15,2) NOT NULL,
    FMC_IMPTOTTACD DECIMAL(15,2) NOT NULL,
    FMC_IMPTOTAL DECIMAL(15,2) NOT NULL
);

ALTER TABLE METDB.MET_FACTMIBGASCAB
  ADD CONSTRAINT FMC_PK
  PRIMARY KEY (FMC_ID);

CREATE TABLE METDB.MET_FACTMIBGASLIN (
    FML_FMC_ID INT NOT NULL, 
    FML_LINEA INT NOT NULL,
    FML_DESCRIP VARCHAR(255),
    FML_CANTIDAD DECIMAL(15,6),
    FML_UNITP DECIMAL(15,6),
    FML_TOTCOST DECIMAL(15,2) NOT NULL,
    FML_TAXRATE DECIMAL(5,2),
    FML_ARTCODE VARCHAR(50));

ALTER TABLE METDB.MET_FACTMIBGASLIN
  ADD CONSTRAINT FML_PK
  PRIMARY KEY (FML_FMC_ID, FML_LINEA);

ALTER TABLE METDB.MET_FACTMIBGASLIN
  ADD CONSTRAINT FML_FMC_FK
  FOREIGN KEY (FML_FMC_ID) REFERENCES METDB.MET_FACTMIBGASCAB(FMC_ID);

