DROP TABLE METDB.MET_REPARTOSDIARIOSPROV;

CREATE TABLE METDB.MET_REPARTOSDIARIOSPROV (
    RDP_ID INT IDENTITY(1, 1) NOT NULL,
    RDP_FEC DATE NOT NULL,
    RDP_PEDIDO INT NOT NULL,
    RDP_INFRASTRUCT VARCHAR(100),
    RDP_PUNTO VARCHAR(100),
    RDP_DESTINO VARCHAR(100),
    RDP_PORCENT_DESTINO DECIMAL(10,2),
    RDP_USOGAS VARCHAR(100),
    RDP_CDM VARCHAR(100),
    RDP_PORCENT_REPARTO DECIMAL(10,2),
    RDP_REPARTO VARCHAR(100),
    RDP_CANTIDAD INT,
    RDP_ORIGEN VARCHAR(100),
    RDP_TITULAR VARCHAR(100),
    RDP_ALBARAN INT,
    RDP_HORA TIME,
    RDP_TOT_CISTERNA INT,
    RDP_PCS DECIMAL(10, 4)
);

ALTER TABLE METDB.MET_REPARTOSDIARIOSPROV
  ADD CONSTRAINT RDP_PK
  PRIMARY KEY (RDP_ID);

DROP TABLE METDB.MET_REPARTOSDIARIOSFINALPROV;

CREATE TABLE METDB.MET_REPARTOSDIARIOSFINALPROV (
    RDFP_ID INT IDENTITY(1, 1) NOT NULL,
    RDFP_FEC DATE NOT NULL,
    RDFP_PEDIDO INT NOT NULL,
    RDFP_INFRASTRUCT VARCHAR(100),
    RDFP_PUNTO VARCHAR(100),
    RDFP_DESTINO VARCHAR(100),
    RDFP_PORCENT_DESTINO DECIMAL(10,2),
    RDFP_USOGAS VARCHAR(100),
    RDFP_CDM VARCHAR(100),
    RDFP_PORCENT_REPARTO DECIMAL(10,2),
    RDFP_REPARTO VARCHAR(100),
    RDFP_CANTIDAD INT,
    RDFP_ORIGEN VARCHAR(100),
    RDFP_TITULAR VARCHAR(100),
    RDFP_ALBARAN INT,
    RDFP_HORA TIME,
    RDFP_TOT_CISTERNA INT,
    RDFP_PCS  DECIMAL(10, 4)
);

ALTER TABLE METDB.MET_REPARTOSDIARIOSFINALPROV
  ADD CONSTRAINT RDFP_PK
  PRIMARY KEY (RDFP_ID);

DROP TABLE METDB.MET_REPARTOSDIARIOSFINALDEF;

CREATE TABLE METDB.MET_REPARTOSDIARIOSFINALDEF (
    RDFD_ID INT IDENTITY(1, 1) NOT NULL,
    RDFD_FEC DATE NOT NULL,
    RDFD_PEDIDO INT NOT NULL,
    RDFD_INFRASTRUCT VARCHAR(100),
    RDFD_PUNTO VARCHAR(100),
    RDFD_DESTINO VARCHAR(100),
    RDFD_PORCENT_DESTINO DECIMAL(10,2),
    RDFD_USOGAS VARCHAR(100),
    RDFD_CDM VARCHAR(100),
    RDFD_PORCENT_REPARTO DECIMAL(10,2),
    RDFD_REPARTO VARCHAR(100),
    RDFD_CANTIDAD INT,
    RDFD_ORIGEN VARCHAR(100),
    RDFD_TITULAR VARCHAR(100),
    RDFD_ALBARAN INT,
    RDFD_HORA TIME,
    RDFD_TOT_CISTERNA INT,
    RDFD_PCS DECIMAL(10, 4)
);

ALTER TABLE METDB.MET_REPARTOSDIARIOSFINALDEF
  ADD CONSTRAINT RDFD_PK
  PRIMARY KEY (RDFD_ID);